// src/components/Course/index.tsx
import Taro, { useState, useEffect } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './index.scss'

interface IProps {
  course: {
    color: string
    course_day: number
    course_id: number
    course_location: string
    course_name: string
    course_teacher: string
    course_time: string
    course_week: string
  }
}

export default (props: IProps) => {
  const [classList, setClassList] = useState(new Array())
  const course = props.course
  useEffect(() => {
    const [course_start, course_end] = course.course_time.split('-').map(v => Number(v))
    const courseLen = course_end - course_start
    const courseDay = course.course_day
    setClassList(() => [
      'course',
      `row-${courseLen + 1}`,
      `top-${course_start}`,
      `left-${courseDay}`
    ])
    // 设为空数组，只会执行一次
  }, [])
  return (
    <View
      className={classList.join(' ')}
      onClick={() => console.log(props)}
      style={{ background: course.color }}
    >
      <View className="course-name">{course.course_name}</View>
      <View className="course-location">{course.course_location}</View>
    </View>
  )
}

// src/components/course.vue
<template>
  <div 
    :class="classList"
    :style="{ 'background': course.color }"
  >
    <div class="course-name">{{ course.course_name }}</div>
    <div class="course-location">{{ course.course_location }}</div>
  </div>
</template>

<script>
export default {
  name: 'Cession',
  props: {
    course: Object
  },
  computed: {
    classList() {
      let [ course_start, course_end ] = this.course.course_time.split('-'); 
      let courseLen = course_end - course_start;
      let courseDay = this.course.course_day;
      return ['course', `row-${courseLen+1}`, `top-${course_start}`, `left-${courseDay}`];
    }
  },
  mounted() {

  }
}
</script>

<style lang="less" scoped>
.course {
  position: absolute;
  z-index: 3;
  width: 50px;
  border: 1px dotted #ccc;
  box-sizing: border-box;
  border-radius: 5px;
  font-size: 12px;
  padding: 5px;
  color: #fff;
}

.row-1 {
  height: 60px;
}
.row-2 {
  height: 120px;
}

.row-3 {
  height: 180px;
}

.row-4 {
  height: 240px;
}

.row-8 {
  height: 480px;
}

.top-1 {
  top: 0
}

.top-3 {
  top: 120px;
}

.top-5 {
  top: 240px;
}

.top-7 {
  top: 360px;
}

.top-9 {
  top: 480px;
}

.left-1 {
  left: 0px;
}

.left-2 {
  left: 50px;
}

.left-3 {
  left: 100px;
}

.left-4 {
  left: 150px;
}

.left-5 {
  left: 200px;
}

.left-6 {
  left: 250px;
}

.left-7 {
  left: 300px;
}
</style>
